### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by daarond** [Tomtomgo/phearjs#1]
Installing on OSX. These are my steps so far:
1. Node Install from .pkg
2. npm install phantomjs
3. I used brew to install memcached: brew install memcached
4. git clone https://github.com/Tomtomgo/phearjs.git
5. cd phearjs
6. npm install
7. memcached -d -p 11211
8. node phear.js

It appears to start normally on 8100, ending in "Phear started"

Getting no response from curl:
curl -X GET "http://localhost:8100?fetch_url=http%3A%2F%2Fwww.apple.com"

Getting no response from chrome browser:
http://localhost:8100/?fetch_url=http%3A%2F%2Fwww.apple.com

Any ideas?

**Comment by Tomtomgo** [comment]
A difference between your installation steps and the ones described [here](https://github.com/Tomtomgo/phearjs/blob/master/INSTALLATION.md) is that you're installing PhantomJS via an NPM package. This might install PhantomJS a little different.

Normally, the last line after starting PhearJS would be a number of messages stating that the workers started:

```
2015-04-07 11:49:26 [         worker:8183] Running PhantomJS worker.
```

If this doesn't show then it could well be that PhantomJS isn't installed correctly. Can you verify that it's installed by running `phantomjs -v` in your terminal?

**Comment by daarond** [comment]
Thanks for the reply Tom. The issue did appear to be from the npm install. I installed with brew instead and now the browser causes an error:

2015-04-07 18:29:19 [          phear:8100] Starting Phear...
2015-04-07 18:29:19 [          phear:8100] ==================================
2015-04-07 18:29:19 [          phear:8100] Mode: development
2015-04-07 18:29:19 [          phear:8100] Config file: ./config/config.json
2015-04-07 18:29:19 [          phear:8100] Port: 8100
2015-04-07 18:29:19 [          phear:8100] Workers: 4
2015-04-07 18:29:19 [          phear:8100] ==================================
2015-04-07 18:29:19 [          phear:8100] Worker 1 of 4 started.
2015-04-07 18:29:19 [          phear:8100] Worker 2 of 4 started.
2015-04-07 18:29:19 [          phear:8100] Worker 3 of 4 started.
2015-04-07 18:29:19 [          phear:8100] Worker 4 of 4 started.
2015-04-07 18:29:19 [          phear:8100] Phear started.
2015-04-07 18:29:20 [         worker:8186] Running PhantomJS worker.
2015-04-07 18:29:20 [         worker:8183] Running PhantomJS worker.
2015-04-07 18:29:20 [         worker:8184] Running PhantomJS worker.
2015-04-07 18:29:20 [         worker:8185] Running PhantomJS worker.
2015-04-07 18:29:31 [          phear:8100] UNCAUGHT ERROR: Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (/Users/MyMac/phearjs/node_modules/request/request.js:946:30)
    at Request.end (/Users/MyMac/phearjs/node_modules/request/request.js:1514:10)
    at end (/Users/MyMac/phearjs/node_modules/request/request.js:717:14)
    at Immediate._onImmediate (/Users/MyMac/phearjs/node_modules/request/request.js:731:7)
    at processImmediate [as _immediateCallback](timers.js:358:17)
2015-04-07 18:29:31 [          phear:8100] Kill process and workers.
node.js:609
        throw new TypeError('invalid pid');
              ^
TypeError: invalid pid
    at process.kill (node.js:609:15)
    at stop (/Users/MyMac/phearjs/phear.js:139:20)
    at process.<anonymous> (/Users/MyMac/phearjs/phear.js:186:12)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)

My phantomjs -v response is 2.0.0

I haven't put this into the IntelliJ debugger, but that's my next step. If you see something already, I appreciate any help.

**Comment by Tomtomgo** [comment]
That's weird, can you check which version of nodejs you're running by doing `node -v`?

**Comment by Tomtomgo** [comment]
Did you manage to get it running? Let me know so I can close the issue.

**Comment by daarond** [comment]
No, didn't manage to get it running, just dropped back to phantom. Feel
free to close it and thanks for following up.

**Comment by Tomtomgo** [comment]
Okay, let me know if you want to give it another go and I'll be glad to help you out.
