### ISSUE TITLE
Not able to install @ Windows 10 x64

### ISSUE THREAD

**Issue by AymanEG** [Tomtomgo/phearjs#18]
Hello there,

I tried to install @ Windows ,but failed , ofcourse I dont have memcached ,butI do have bitnami stack which I can install through : https://bitnami.com/stack/memcached

Anyway I am not interested in caching now,so
1- I have Node js installed
2- I have phantom js last version
3- No Memcached yet
4- Followed this code : 

```
git clone https://github.com/Tomtomgo/phearjs.git
cd phearjs
npm install
```
The installation create error and debug log is attached.

[npm-debug.txt](https://github.com/Tomtomgo/phearjs/files/687400/npm-debug.txt)

Now starting the service with : node phearjs , getting this error

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Bitnami\phearjs\phearjs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by themenucha** [comment]
Same here on Win10x64....
