### ISSUE TITLE
Troubles then I am trying to install phearjs

### ISSUE THREAD

**Issue by Avena83** [Tomtomgo/phearjs#8]
# Please help me. Many thanks.

What I have here:

```
root@sv2:~/phearjs# cat /etc/issue
Debian GNU/Linux 8 \n \l
root@sv2:~/phearjs# cat /etc/debian_version
8.4
root@sv2:~/phearjs# uname -m
x86_64
root@sv2:~/phearjs# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.4 (jessie)
Release:        8.4
Codename:       jessie
root@sv2:~/phearjs# nodejs -v
v0.10.29
root@sv2:~/phearjs# npm -v
1.4.21
root@sv2:~/phearjs# memcached -help | grep memcached
memcached 1.4.21
root@sv2:~/phearjs# ls
assets  build  CHANGELOG.md  config  gulpfile.js  INSTALLATION.md  lib  node_modules  npm-debug.log  package.json  phear.js  README.md  restart_worker.sh  src
```

How I am trying to install:
root@sv2:~/phearjs# npm install
and got

```
npm WARN package.json gulp-load-plugins@1.2.4 No README data
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
\
> usage@0.7.1 install /root/phearjs/node_modules/usage
> node-gyp rebuild

make: Entering directory '/root/phearjs/node_modules/usage/build'
  CXX(target) Release/obj.target/sysinfo/src/binding.o
In file included from ../src/binding.cpp:2:0:
../node_modules/nan/nan.h:324:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
sysinfo.target.mk:88: recipe for target 'Release/obj.target/sysinfo/src/binding.o' failed
make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
make: Leaving directory '/root/phearjs/node_modules/usage/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/phearjs/node_modules/usage
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! usage@0.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usage@0.7.1 install script.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/phearjs
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/phearjs/npm-debug.log
npm ERR! not ok code 0
```

Please help me to solve this issue. Thanks

**Comment by Tomtomgo** [comment]
Hi @Avena83, it could well be that your NodeJS version is too old. Maybe try updating first (https://nodejs.org/en/) and then install Phear. Does that work?

**Comment by Avena83** [comment]
@Tomtomgo Thanks a lot. Now it's working. Thanks.

**Comment by Avena83** [comment]
Install finished like:
...

```
phearjs@0.5.0 /root/phearjs
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   └─┬ glob-stream@3.1.18
│     └─┬ through2@0.6.5 
│       └─┬ readable-stream@1.0.34 
│         └── isarray@0.0.1 
├─┬ gulp-insert@0.5.0
│ └─┬ streamqueue@0.0.6
│   └─┬ readable-stream@1.1.14 
│     └── isarray@0.0.1 
├─┬ gulp-util@3.0.7
│ └─┬ dateformat@1.0.12
│   └─┬ meow@3.7.0
│     └── minimist@1.2.0 
├─┬ request@2.72.0
│ └─┬ http-signature@1.1.1
│   └─┬ sshpk@1.8.3
│     ├─┬ dashdash@1.14.0
│     │ └── assert-plus@1.0.0 
│     └─┬ getpass@0.1.6
│       └── assert-plus@1.0.0 
└─┬ usage@0.7.1 
  ├── bindings@1.2.1 
  └── nan@2.3.5 

npm WARN phearjs@0.5.0 No license field.

```

last step has again troubles

```
root@sv2:~/phearjs# node phearjs 
module.js:442
    throw err;
    ^

Error: Cannot find module '/root/phearjs/phearjs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
root@sv2:~/phearjs#
```

**Comment by Tomtomgo** [comment]
Try running:

``` shell
node phear.js 
```

**Comment by Avena83** [comment]
@Tomtomgo Thanks a lot for your help. All things is working nice. Good job !
